---
include:
 # - board: eyelash_sofle_left
#    shield: nice_view
  - board: eyelash_sofle_right
    shield: nice_view_custom
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args:
      - -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_KSCAN_MATRIX_POLL_PERIOD_US=8000
      - -DCONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=12
    artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
  - board: eyelash_sofle_right
    shield: settings_reset
